#!/bin/bash

WALLPAPER_DIR="$HOME/wallpapers/"
export SWWW_TRANSITION=random
export SWWW_TRANSITION_FPS=120
export SWWW_TRANSITION_DURATION=5

WALLPAPER=$(ls $WALLPAPER_DIR | fuzzel -d -R)
swww img "$WALLPAPER_DIR/$WALLPAPER"
