
[subtitles]

	[subtitles.general]
		show_subtitles = true
		show_unknown_subtitles = true

	[subtitles.subtitle_color]
		subtitle_alpha = 0

	[subtitles.subtitle_pos]
		subtitle_x = 1236
		subtitle_y = 793

	[subtitles.subtitle_scale]
		subtitle_scale = 100

