night_light = { enabled = true, start_time = "00:01", end_time = "23:59", temperature = 7000 }

vibrance_configs = [
  { window_class = ".", window_title = ".", strength = 100 },
]

hot_reload = true
