[general]
live_config_reload = true
ipc_socket = true
import = ["~/.cache/wal/colors-alacritty.toml"]

[window]
padding = { x = 20 , y = 20 }
decorations = "full"
dynamic_title = true

[font]
normal = { family = "Commit Mono Nerd Font", style = "Regular"}
size = 10.0
offset = { y = 4}

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }
