[general]
live_config_reload = true
ipc_socket = true
import = ["~/.cache/wal/colors-alacritty.toml"]

[window]
padding = { x = 40 , y = 40 }
decorations = "full"
dynamic_title = true

[font]
normal = { family = "Terminess Nerd Font Mono", style = "Regular"}
size = 12.0
offset = { y = 4}

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }
