#!/usr/bin/env bash

# kill picom dunst polkit and polybar
killall -9 polybar picom dunst polkit-kde-authentication-agent-1 polkit-gnome-authentication-agent-1

# compose
picom &

# wallpaper
nitrogen --restore &

# polkit
/usr/libexec/polkit-gnome-authentication-agent-1 &

# notif demon
dunst &

# dock
#plank &

# xkbd
setxkbmap -layout "us" &

# bar
polybar &

# copy n paste
xclip
